#!/usr/bin/env python3
"""Manage the machine-owned Markdown lessons layer.

Lessons live in .artifacts/LESSONS.md. A lesson enters as a candidate grounded
in a real signal, becomes confirmed across two distinct features, and becomes
quarantined after two penalties. Only confirmed lessons are guidance.
"""

import argparse
import datetime
import os
import re
import sys
import unicodedata


CODES = [
    "agreed-behavior",
    "test-case",
    "test-suite",
    "planned-task",
    "source-code",
    "spec-defect",
    "open-question",
]
STATUSES = ["candidate", "confirmed", "quarantined"]
CONFIRM_FEATURE_THRESHOLD = 2
QUARANTINE_PENALTY_THRESHOLD = 2
FIELD_SEPARATOR = " — "
ENTRY_PATTERN = re.compile(r"^-\s+(.+?)\s+—\s+(.+?)\s+—\s+signal:\s+([^—]+?)\s+—\s+features:\s+([^—]+?)\s+—\s+sources:\s+(.+?)\s*(?:—\s+penalized on\s+(.+?))?$")
SIGNAL_ROW_PATTERN = re.compile(r"^\|\s*([^|]+?)\s*\|\s*[^|]+\s*\|\s*[^|]+\s*\|\s*[^|]+\s*\|\s*(open|resolved)\s*\|$")


def today():
    return datetime.date.today().isoformat()


def normalize(text):
    text = unicodedata.normalize("NFD", text.casefold())
    text = "".join(char for char in text if unicodedata.category(char) != "Mn")
    text = "".join(char if char.isalnum() or char.isspace() else " " for char in text)
    return re.sub(r"\s+", " ", text).strip()


def read_lessons(path):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            lines = handle.read().splitlines()
    except FileNotFoundError:
        return []
    except (OSError, UnicodeDecodeError) as error:
        raise ValueError("could not read %s: %s" % (path, error)) from error

    lessons = []
    section = None
    for line_number, line in enumerate(lines, 1):
        heading = re.match(r"^##\s+(.+?)\s*$", line)
        if heading:
            section = heading.group(1).strip()
            continue
        if not line.startswith("- "):
            continue
        match = ENTRY_PATTERN.match(line)
        if section not in ("Confirmed", "Candidates", "Quarantined") or not match:
            raise ValueError("invalid lesson entry at line %d" % line_number)
        identifier, text, signal, features, sources, penalties = match.groups()
        if not re.fullmatch(r"L-\d+", identifier.strip()):
            raise ValueError("invalid lesson id at line %d" % line_number)
        status = {"Confirmed": "confirmed", "Candidates": "candidate", "Quarantined": "quarantined"}[section]
        lessons.append({
            "id": identifier.strip(),
            "text": text.strip(),
            "signal": signal.strip(),
            "features": split_values(features),
            "sources": split_values(sources),
            "penalties": split_values(penalties or ""),
            "status": status,
        })
    return lessons


def split_values(value):
    return [item.strip() for item in value.split(",") if item.strip() and item.strip() != "-"]


def id_key(lesson):
    match = re.search(r"(\d+)$", lesson.get("id", ""))
    return int(match.group(1)) if match else 0


def next_id(lessons):
    return "L-%03d" % (max((id_key(lesson) for lesson in lessons), default=0) + 1)


def section_for(lesson):
    if len(set(lesson["penalties"])) >= QUARANTINE_PENALTY_THRESHOLD:
        return "quarantined"
    if len(set(lesson["features"])) >= CONFIRM_FEATURE_THRESHOLD:
        return "confirmed"
    return "candidate"


def render(lessons):
    lines = [
        "# LESSONS - machine-owned by scripts/lessons.py",
        "",
        "> Do not edit this file by hand. The script rewrites it on every change.",
        "",
    ]
    for section in ("confirmed", "candidate", "quarantined"):
        title = section.title() if section != "candidate" else "Candidates"
        lines.extend(["## %s" % title, ""])
        entries = sorted((lesson for lesson in lessons if lesson["status"] == section), key=id_key)
        if not entries:
            lines.extend(["_none_", ""])
            continue
        for lesson in entries:
            line = (
                "- %s — %s — signal: %s — features: %s — sources: %s"
                % (
                    lesson["id"],
                    lesson["text"],
                    lesson["signal"],
                    ", ".join(sorted(set(lesson["features"]))) or "-",
                    ", ".join(sorted(set(lesson["sources"]))) or "-",
                )
            )
            if lesson["penalties"]:
                line += " — penalized on " + ", ".join(sorted(set(lesson["penalties"])))
            lines.extend([line, ""])
    return "\n".join(lines).rstrip() + "\n"


def write_lessons(path, lessons):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    temporary_path = path + ".tmp"
    with open(temporary_path, "w", encoding="utf-8") as handle:
        handle.write(render(lessons))
    os.replace(temporary_path, path)


def signal_source_exists(source, feature, signal):
    source_path, separator, anchor = source.partition("#")
    if not separator or not anchor.isdigit() or int(anchor) < 1:
        return False
    if os.path.basename(source_path) != "SIGNALS.md":
        return False
    if os.path.basename(os.path.dirname(os.path.normpath(source_path))) != feature:
        return False
    try:
        with open(source_path, "r", encoding="utf-8") as handle:
            lines = handle.read().splitlines()
    except (OSError, UnicodeDecodeError):
        return False
    signal_rows = [match.groups() for line in lines if (match := SIGNAL_ROW_PATTERN.match(line))]
    row_index = int(anchor) - 1
    return row_index < len(signal_rows) and signal_rows[row_index][0].strip() == signal


def find_by_text(lessons, text):
    key = normalize(text)
    return next((lesson for lesson in lessons if normalize(lesson["text"]) == key), None)


def cmd_add(args):
    if args.signal not in CODES:
        raise ValueError("--signal must be one of %s" % ", ".join(CODES))
    if not args.text.strip() or not args.feature.strip() or not args.source.strip():
        raise ValueError("--text, --feature, and --source must not be empty")
    feature = args.feature.strip()
    source = args.source.strip()
    if FIELD_SEPARATOR in args.text:
        raise ValueError("--text must not contain the lesson field separator")
    if not signal_source_exists(source, feature, args.signal):
        raise ValueError("the source must identify the signal row in the named feature")

    lessons = read_lessons(args.store)
    existing = find_by_text(lessons, args.text)
    if existing:
        if existing["status"] == "quarantined":
            raise ValueError("a quarantined lesson cannot be reactivated")
        if feature in existing["features"]:
            raise ValueError("the lesson already exists for this feature")
        existing["features"].append(feature)
        existing["sources"].append(source)
        existing["status"] = section_for(existing)
        target = existing
    else:
        target = {
            "id": next_id(lessons),
            "text": args.text.strip(),
            "signal": args.signal,
            "features": [feature],
            "sources": [source],
            "penalties": [],
            "status": "candidate",
            "created": today(),
        }
        lessons.append(target)
    write_lessons(args.store, lessons)
    print("%s %s: %s" % (target["id"], target["status"], target["text"]))
    return 0


def cmd_list(args):
    lessons = read_lessons(args.store)
    status = args.status or "confirmed"
    for lesson in sorted((item for item in lessons if item["status"] == status), key=id_key):
        print(
            "%s [%s] %s (signal: %s; features: %s)"
            % (lesson["id"], lesson["status"], lesson["text"], lesson["signal"], ", ".join(lesson["features"]))
        )
    return 0


def cmd_penalize(args):
    lessons = read_lessons(args.store)
    target = next((lesson for lesson in lessons if lesson["id"] == args.id), None)
    if not target:
        raise ValueError("no lesson with id %s" % args.id)
    if target["status"] != "confirmed":
        raise ValueError("only confirmed lessons can be penalized")
    if args.feature in target["penalties"]:
        raise ValueError("lesson already penalized for this feature")
    target["penalties"].append(args.feature)
    target["status"] = section_for(target)
    write_lessons(args.store, lessons)
    print("%s %s" % (target["id"], target["status"]))
    return 0


def cmd_normalize(args):
    lessons = read_lessons(args.store)
    merged = {}
    for lesson in lessons:
        key = normalize(lesson["text"])
        if key not in merged:
            merged[key] = lesson
            continue
        target = merged[key]
        target["features"] = sorted(set(target["features"] + lesson["features"]))
        target["sources"] = sorted(set(target["sources"] + lesson["sources"]))
        target["penalties"] = sorted(set(target["penalties"] + lesson["penalties"]))
        target["status"] = "quarantined" if "quarantined" in (target["status"], lesson["status"]) else section_for(target)
        if id_key(lesson) < id_key(target):
            target["id"] = lesson["id"]
    write_lessons(args.store, list(merged.values()))
    print("NORMALIZED %d lessons" % len(merged))
    return 0


def build_parser():
    parser = argparse.ArgumentParser(description="Manage the Markdown lessons layer.")
    parser.add_argument("--store", default=os.path.join(".artifacts", "LESSONS.md"))
    subcommands = parser.add_subparsers(dest="command", required=True)

    add = subcommands.add_parser("add")
    add.add_argument("--text", required=True)
    add.add_argument("--signal", required=True)
    add.add_argument("--source", required=True)
    add.add_argument("--feature", required=True)
    add.set_defaults(func=cmd_add)

    listing = subcommands.add_parser("list")
    listing.add_argument("--status", choices=STATUSES, default="confirmed")
    listing.set_defaults(func=cmd_list)

    penalize = subcommands.add_parser("penalize")
    penalize.add_argument("--id", required=True)
    penalize.add_argument("--feature", required=True)
    penalize.set_defaults(func=cmd_penalize)

    normalize_command = subcommands.add_parser("normalize")
    normalize_command.set_defaults(func=cmd_normalize)
    return parser


def main(argv=None):
    try:
        args = build_parser().parse_args(argv)
        return args.func(args)
    except (OSError, ValueError) as error:
        sys.stderr.write("error: %s\n" % error)
        return 2


if __name__ == "__main__":
    sys.exit(main())
